[tool.poetry]
name = "projeto-pratico"
version = "0.1.0"
description = ""
authors = ["Wendel"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.41.1"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
